# -*- coding: utf-8 -*-
"""Password Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bOMohDu0g3DrJVOiZFhvDqZstRRF7_N
"""

import random
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    while True:
        print("Enter Username")
        username = input()

        print("Enter Password Length")
        try:
            password_length = int(input())
            if password_length <= 0:
                print("Password length should be a positive number.")
                continue
            password = generate_password(password_length)
            print(f"Generated Password: {password}")
        except ValueError:
            print("Please enter a valid number for password length.")

        print("Reset? (y/n)")
        reset = input().lower()
        if reset != "y":
            print("Thank You!")
            break

if __name__ == "__main__":
    main()